{{! Template used to generate workflow file with shared-enviroments }}
{{=[[ ]]=}}
name: Canary Deployment us-east-2

on:
  push:
    branches: [canary]

jobs:
  deploy:
    name: Gateway
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Make envfile us-east-2
        uses: SpicyPizza/create-envfile@v1
        with:
          [[#shared_envs]]
          envkey_[[key]]: [[&value]]
          [[/shared_envs]]
          envkey_REDIS_ENDPOINT: gateway-canary.pzdhdc.ng.0001.use2.cache.amazonaws.com:6379
          envkey_REGION: 'us-east-2'
          envkey_REGION_NAME: '/canary/us-east-2'
          file_name: .env

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: gateway-canary
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

      - name: Fill in the new image ID / us-east-2 - gateway
        id: task-def-us-east-2-gateway
        uses: aws-actions/amazon-ecs-render-task-definition@master
        with:
          task-definition: pocket-gateway/tasks/canary/us-east-2/ecs-task-us-east-2.json
          container-name: gateway-canary
          image: ${{ steps.build-image.outputs.image }}
          # Needs to be set at container level to be read by the dd agent
          environment-variables: |
            DD_RUNTIME_METRICS_ENABLED=true
            DD_SERVICE=/canary/us-east-2/ecs/gateway
            DD_VERSION=${{ github.sha }}
            DD_ENV=canary

      - name: Fill in the new image ID / us-east-2 - datadog-agent
        id: task-def-us-east-2-datadog-agent
        uses: aws-actions/amazon-ecs-render-task-definition@master
        with:
          task-definition: ${{ steps.task-def-us-east-2-gateway.outputs.task-definition }}
          container-name: datadog-agent
          image: datadog/agent:latest
          environment-variables: |
            DD_API_KEY=${{ secrets.DATADOG_API_KEY }}
            DD_SITE=datadoghq.eu
            DD_LOGS_ENABLED=false
            DD_APM_ENABLED=true
            DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
            ECS_FARGATE=true

      - name: Deploy / us-east-2
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def-us-east-2-datadog-agent.outputs.task-definition }}
          service: gateway-service
          cluster: gateway-canary
          wait-for-service-stability: true
